development:
  host: localhost:3000
  handle: twonewnatives
  email: ianmilliken@live.co.uk
  api_key: 98e557ec722a1a693e56d67531e4a1fec06de447

# staging:
#   host: staging.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>

# production:
#   host: www.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
#   # ssl: true
